###
POST http://localhost:3000/api/wishes
Content-type: application/json

{
    "message": "Anh thật sự thích em"
}

###
POST http://localhost:3000/api/prophecies
Content-type: Application/json 

{
    "date": "17/08/2006"
}