###
POST http://localhost:3000/api/wishes
Content-type: application/json

{
    "message": "Em muốn nói với anh rằng anh là cả cuộc đời em. Yêu anh tận sâu thẳm trong trái tim. Em ko thể thiếu anh. Anh là tình yêu của em. Năm mới em chúc cho tình yêu của chúng mình mãi đẹp như thủa ban đầu luôn cháy bỏng anh nhé!"
}

###
POST http://localhost:3000/api/prophecies
Content-type: Application/json 

{
    "date": "17/08/2006"
}